import React, { useState, useRef } from 'react'
import { FlaskConical, Sparkles, Loader2, X, CheckCircle2, AlertTriangle, Clock, RotateCcw, FileText, Share2, ChevronDown } from 'lucide-react'
import { toast } from 'react-toastify'
import { analyzeReport } from '../services/aiService'

const STATUS_STYLE = {
  Normal:     { text: 'text-emerald-700 dark:text-emerald-400', bg: 'bg-emerald-50 dark:bg-emerald-900/20', icon: CheckCircle2 },
  Borderline: { text: 'text-amber-700 dark:text-amber-400',    bg: 'bg-amber-50 dark:bg-amber-900/20',    icon: Clock        },
  Abnormal:   { text: 'text-red-700 dark:text-red-400',        bg: 'bg-red-50 dark:bg-red-900/20',        icon: AlertTriangle },
}

const URGENCY_BADGE = {
  Routine: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400',
  Soon:    'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400',
  Urgent:  'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
}

const STEPS = ['Parsing report', 'Extracting values', 'Analysing findings', 'Generating insights']

const REPORT_TYPES = [
  'Blood Sugar / Diabetes Panel', 'Complete Blood Count (CBC)', 'Lipid Profile',
  'Thyroid Function Test (TFT)', 'Kidney Function Test (KFT)', 'Liver Function Test (LFT)',
  'Urine Analysis', 'ECG Report', 'X-Ray Report', 'MRI Report', 'CT Scan Report', 'Other',
]

const SAMPLE_REPORTS = {
  'Complete Blood Count (CBC)': `Haemoglobin (Hb): 13.4 g/dL (Ref: 12–17)
WBC Count: 7,200 cells/µL (Ref: 4,500–11,000)
Platelet Count: 210,000 /µL (Ref: 150,000–400,000)
Fasting Blood Sugar: 102 mg/dL (Ref: 70–100)
HbA1c: 5.8% (Ref: < 5.7%)`,
  'Lipid Profile': `Total Cholesterol: 198 mg/dL (Ref: < 200)
HDL: 42 mg/dL (Ref: > 60)
LDL: 132 mg/dL (Ref: < 100)
Triglycerides: 168 mg/dL (Ref: < 150)`,
}

const ReportAnalysisAgent = ({ open, onClose }) => {
  const [reportText, setReportText] = useState('')
  const [reportType, setReportType] = useState('Complete Blood Count (CBC)')
  const [result, setResult] = useState(null)
  const [loading, setLoading] = useState(false)
  const [step, setStep] = useState(0)

  const resetState = () => {
    setReportText('')
    setResult(null)
    setLoading(false)
    setStep(0)
  }

  const loadSample = () => {
    const sample = SAMPLE_REPORTS[reportType]
    if (sample) setReportText(sample)
    else toast.info('No sample available for this report type. Please paste your own report text.')
  }

  const analyze = async () => {
    if (!reportText.trim()) { toast.warn('Please paste your report content first'); return }
    setLoading(true)
    setStep(0)

    // Animate progress steps
    let s = 0
    const interval = setInterval(() => {
      s++
      setStep(s)
      if (s >= STEPS.length - 1) clearInterval(interval)
    }, 600)

    try {
      const res = await analyzeReport(reportText, reportType)
      clearInterval(interval)
      setStep(STEPS.length - 1)
      const data = res?.data || res
      setResult(data)
    } catch {
      clearInterval(interval)
      toast.error('Report analysis failed. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  const copyForDoctor = () => {
    if (!result) return
    const text = [
      `AI Report Analysis — ${result.reportType}`,
      '',
      result.summary,
      '',
      'KEY FINDINGS:',
      ...(result.keyFindings || []).map(f => `• ${f.parameter}: ${f.value} (${f.normalRange}) — ${f.status}`),
      '',
      'RECOMMENDATIONS:',
      result.recommendations,
      '',
      '[Generated by MediLink AI Report Analyser]',
    ].join('\n')
    navigator.clipboard?.writeText(text)
      .then(() => toast.success('Summary copied to clipboard'))
      .catch(() => toast.info('Please copy the summary manually'))
  }

  if (!open) return null

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} />
      <div className="relative w-full max-w-lg bg-white dark:bg-gray-900 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">

        {/* Header */}
        <div className="px-5 py-4 flex items-center justify-between bg-gradient-to-r from-emerald-600 to-teal-600 flex-shrink-0">
          <div className="flex items-center gap-3">
            <FlaskConical className="w-5 h-5 text-white" />
            <h2 className="font-bold text-white text-base">AI Report Analysis</h2>
            <span className="text-[10px] bg-white/20 text-white px-2 py-0.5 rounded-full font-medium uppercase tracking-wide">LLM Powered</span>
          </div>
          <button onClick={onClose} className="text-white/70 hover:text-white transition p-1">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-5 space-y-4">
          {!result ? (
            <>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Select your report type and paste the report text. Our AI will extract values, flag abnormals, and generate clinical insights.
              </p>

              {/* Report type selector */}
              <div>
                <label className="text-xs font-semibold uppercase tracking-wide text-gray-400 block mb-1.5">Report Type</label>
                <div className="relative">
                  <select
                    value={reportType}
                    onChange={e => setReportType(e.target.value)}
                    className="w-full text-sm px-3 py-2.5 pr-8 rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-emerald-500 outline-none appearance-none"
                  >
                    {REPORT_TYPES.map(t => <option key={t}>{t}</option>)}
                  </select>
                  <ChevronDown className="w-4 h-4 text-gray-400 absolute right-2.5 top-3 pointer-events-none" />
                </div>
              </div>

              {/* Text area */}
              <div>
                <div className="flex items-center justify-between mb-1.5">
                  <label className="text-xs font-semibold uppercase tracking-wide text-gray-400">Report Content</label>
                  <button
                    onClick={loadSample}
                    className="text-[10px] text-emerald-600 dark:text-emerald-400 hover:underline font-medium"
                  >
                    Load sample
                  </button>
                </div>
                <textarea
                  value={reportText}
                  onChange={e => setReportText(e.target.value)}
                  placeholder={`Paste your ${reportType} values here…\nExample:\nHaemoglobin: 13.4 g/dL\nWBC: 7200 cells/µL`}
                  rows={7}
                  className="w-full text-sm px-3 py-2.5 rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800 text-gray-900 dark:text-white placeholder-gray-400 focus:ring-2 focus:ring-emerald-500 outline-none resize-none font-mono"
                />
                <p className="text-[10px] text-gray-400 mt-1">Tip: Copy values from your lab report and paste them above, or use the "Load sample" button to try a demo.</p>
              </div>

              {/* Progress steps */}
              {loading && (
                <div className="space-y-2">
                  {STEPS.map((s, i) => (
                    <div key={i} className="flex items-center gap-3">
                      <div className={`w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 ${i < step ? 'bg-emerald-500' : i === step ? 'bg-emerald-500 animate-pulse' : 'bg-gray-200 dark:bg-gray-700'}`}>
                        {i < step ? <CheckCircle2 className="w-3 h-3 text-white" /> : i === step ? <Loader2 className="w-3 h-3 text-white animate-spin" /> : <span className="w-1.5 h-1.5 rounded-full bg-gray-400 block" />}
                      </div>
                      <p className={`text-sm ${i <= step ? 'text-gray-700 dark:text-gray-300 font-medium' : 'text-gray-400'}`}>{s}</p>
                    </div>
                  ))}
                </div>
              )}

              <button
                onClick={analyze}
                disabled={loading || !reportText.trim()}
                className="w-full py-3 bg-gradient-to-r from-emerald-600 to-teal-600 text-white text-sm font-semibold rounded-xl flex items-center justify-center gap-2 hover:from-emerald-700 hover:to-teal-700 disabled:opacity-50 transition shadow-lg shadow-emerald-500/25"
              >
                {loading ? <><Loader2 className="w-4 h-4 animate-spin" /> Analysing…</> : <><Sparkles className="w-4 h-4" /> Analyse Report</>}
              </button>
            </>
          ) : (
            <>
              {/* Report type + urgency header */}
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <FileText className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
                  <p className="text-sm font-bold text-gray-900 dark:text-white">{result.reportType}</p>
                </div>
                <span className={`text-[10px] font-bold uppercase px-2.5 py-1 rounded-full ${URGENCY_BADGE[result.urgency] || URGENCY_BADGE.Routine}`}>
                  {result.urgency}
                </span>
              </div>

              {/* Summary */}
              <div className="rounded-xl bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-900 p-4">
                <p className="text-sm text-emerald-800 dark:text-emerald-300 font-medium">{result.summary}</p>
              </div>

              {/* Key Findings */}
              {result.keyFindings?.length > 0 && (
                <div>
                  <p className="text-xs font-semibold uppercase tracking-wide text-gray-400 mb-2">Key Findings</p>
                  <div className="space-y-2">
                    {result.keyFindings.map((f, i) => {
                      const style = STATUS_STYLE[f.status] || STATUS_STYLE.Normal
                      const Icon = style.icon
                      return (
                        <div key={i} className={`rounded-lg border px-3 py-2.5 ${style.bg} border-transparent`}>
                          <div className="flex items-start gap-3">
                            <Icon className={`w-4 h-4 flex-shrink-0 mt-0.5 ${style.text}`} />
                            <div className="flex-1 min-w-0">
                              <div className="flex items-center justify-between gap-2">
                                <p className="text-xs font-semibold text-gray-700 dark:text-gray-300">{f.parameter}</p>
                                <div className="text-right flex-shrink-0">
                                  <p className={`text-sm font-bold ${style.text}`}>{f.value}</p>
                                  <p className={`text-[10px] font-semibold ${style.text}`}>{f.status}</p>
                                </div>
                              </div>
                              <p className="text-[10px] text-gray-400 mt-0.5">Normal: {f.normalRange}</p>
                              {f.explanation && <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">{f.explanation}</p>}
                            </div>
                          </div>
                        </div>
                      )
                    })}
                  </div>
                </div>
              )}

              {/* Insights */}
              {result.insights?.length > 0 && (
                <div>
                  <p className="text-xs font-semibold uppercase tracking-wide text-gray-400 mb-2">AI Insights</p>
                  <ul className="space-y-1.5">
                    {result.insights.map((ins, i) => (
                      <li key={i} className="flex items-start gap-2 text-sm text-gray-600 dark:text-gray-400">
                        <span className="text-emerald-500 flex-shrink-0">•</span>{ins}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Recommendation */}
              <div className="rounded-xl bg-blue-50 dark:bg-blue-900/20 border border-blue-100 dark:border-blue-900 p-4">
                <p className="text-xs font-bold uppercase tracking-wide text-blue-600 dark:text-blue-400 mb-1.5">Recommendation</p>
                <p className="text-sm text-blue-800 dark:text-blue-300">{result.recommendations}</p>
              </div>

              <p className="text-xs text-gray-400 border-t border-gray-100 dark:border-gray-800 pt-3">
                ⚕️ AI analysis is for informational reference only. Always consult a qualified doctor for clinical interpretation and treatment decisions.
              </p>

              <div className="flex gap-3">
                <button onClick={resetState} className="flex-1 flex items-center justify-center gap-2 py-2.5 rounded-xl border border-emerald-200 dark:border-emerald-800 text-emerald-600 dark:text-emerald-400 text-sm font-medium hover:bg-emerald-50 dark:hover:bg-emerald-900/20 transition">
                  <RotateCcw className="w-4 h-4" /> Analyse Another
                </button>
                <button onClick={copyForDoctor} className="flex-1 flex items-center justify-center gap-2 py-2.5 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 text-white text-sm font-semibold hover:from-emerald-700 hover:to-teal-700 transition shadow-lg shadow-emerald-500/25">
                  <Share2 className="w-4 h-4" /> Copy for Doctor
                </button>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  )
}

export default ReportAnalysisAgent
