'use strict';

/**
 * Central source taxonomy shared by every AI agent response.
 *
 * This module classifies *how a result was actually produced* so the
 * frontend can disclose it honestly instead of calling everything
 * generically "AI". It never changes what an agent computes — it only
 * describes it.
 */

const SOURCE_TYPES = Object.freeze({
  RULES: 'rules',
  RECORDS: 'records',
  LIVE_RECORDS: 'live-records',
  LLM: 'llm',
  DEGRADED_FALLBACK: 'degraded-fallback',
});

const SOURCE_LABELS = Object.freeze({
  [SOURCE_TYPES.RULES]: 'Rules',
  [SOURCE_TYPES.RECORDS]: 'Records',
  [SOURCE_TYPES.LIVE_RECORDS]: 'Live Records',
  [SOURCE_TYPES.LLM]: 'LLM',
  [SOURCE_TYPES.DEGRADED_FALLBACK]: 'Degraded Fallback',
});

const SOURCE_EXPLANATIONS = Object.freeze({
  [SOURCE_TYPES.RULES]: 'Produced by deterministic clinical or operational rules.',
  [SOURCE_TYPES.RECORDS]: 'Derived from stored MediLink records.',
  [SOURCE_TYPES.LIVE_RECORDS]: 'Calculated from the latest available application records.',
  [SOURCE_TYPES.LLM]: 'Generated using a configured language-model provider.',
  [SOURCE_TYPES.DEGRADED_FALLBACK]: 'Generated by fallback logic because the primary provider was unavailable or unsuitable.',
});

/**
 * Classify a result produced through services/ai/llmClient.js's callLLM
 * contract, i.e. an object carrying `_source` ('llm' | 'rules') and,
 * when the LLM path failed, `_degraded: true`.
 *
 * `_degraded` is what distinguishes "rules because this feature never
 * calls an LLM by design" (Health Risk, Patient Summary, ...) from
 * "rules because the LLM call just failed" (Degraded Fallback).
 */
function classifySource(data) {
  if (!data) return SOURCE_TYPES.RULES;
  if (data._source === 'llm') return SOURCE_TYPES.LLM;
  if (data._source === 'rules' && data._degraded) return SOURCE_TYPES.DEGRADED_FALLBACK;
  if (data._source === 'rules') return SOURCE_TYPES.RULES;
  if (data._source === 'records') return SOURCE_TYPES.RECORDS;
  if (data._source === 'live-records') return SOURCE_TYPES.LIVE_RECORDS;
  // A frontend-only local fallback (e.g. the network request itself failed)
  // is still, honestly, a degraded fallback rather than a clean rules result.
  if (data._source === 'local-rules') return SOURCE_TYPES.DEGRADED_FALLBACK;
  return SOURCE_TYPES.RULES;
}

/**
 * Build the disclosure metadata block appended to an agent's response.
 *
 * `forceSourceType` lets an agent state the source of its *substantive*
 * answer explicitly when that differs from whether the LLM attempt
 * succeeded — e.g. Bed Allocation and Appointment Optimizer always
 * recompute their recommendation from a live database query and must
 * never claim the LLM's specific pick was used, even if the LLM call
 * itself succeeded.
 *
 * provider/model are populated only when the classified (or forced)
 * source is genuinely 'llm' — never for rules, records, live-records,
 * or degraded fallback, and never guessed.
 */
function buildSourceMeta(data, options = {}) {
  const { forceSourceType, limitations = [], requiresHumanReview = true } = options;
  const sourceType = forceSourceType || classifySource(data);
  const usedLlm = sourceType === SOURCE_TYPES.LLM;

  return {
    sourceType,
    sourceLabel: SOURCE_LABELS[sourceType],
    sourceExplanation: SOURCE_EXPLANATIONS[sourceType],
    generatedAt: new Date().toISOString(),
    // OpenRouter is the only configured gateway (services/ai/llmClient.js);
    // naming it is not a credential or endpoint disclosure.
    providerUsed: usedLlm ? 'OpenRouter' : null,
    modelUsed: usedLlm ? (data && data._model) || null : null,
    fallbackUsed: sourceType === SOURCE_TYPES.DEGRADED_FALLBACK,
    requiresHumanReview,
    limitations,
  };
}

module.exports = {
  SOURCE_TYPES,
  SOURCE_LABELS,
  SOURCE_EXPLANATIONS,
  classifySource,
  buildSourceMeta,
};
