import jsPDF from 'jspdf'
import 'jspdf/dist/polyfills.es.js'

const BLUE   = [46, 134, 222]
const DARK   = [30, 41, 59]
const MID    = [71, 85, 105]
const LIGHT  = [248, 250, 252]
const BORDER = [226, 232, 240]

const fmt = (n) => `₹${Number(n || 0).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`

export const generateBillPdf = (bill) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const W = 210
  const MARGIN = 16
  const COL = W - MARGIN * 2
  let y = 0

  // ── Header strip ──────────────────────────────────────────────────────────
  doc.setFillColor(...BLUE)
  doc.rect(0, 0, W, 40, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('MediLink Hospital', MARGIN, 17)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text('Hospital Management System', MARGIN, 23)

  // Bill ID + status badge area
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('TAX INVOICE', W - MARGIN, 14, { align: 'right' })
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.text(bill.billNumber || '—', W - MARGIN, 20, { align: 'right' })

  const statusColor = bill.paymentStatus === 'Paid' ? [16, 185, 129] : bill.paymentStatus === 'Partially-Paid' ? [245, 158, 11] : [239, 68, 68]
  doc.setFillColor(...statusColor)
  const statusLabel = bill.paymentStatus || 'Unpaid'
  const sW = doc.getTextWidth(statusLabel) + 8
  doc.roundedRect(W - MARGIN - sW, 24, sW, 7, 2, 2, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(7)
  doc.text(statusLabel, W - MARGIN - sW / 2, 29, { align: 'center' })

  y = 48

  // ── Bill info row ─────────────────────────────────────────────────────────
  doc.setTextColor(...DARK)
  const billDate = bill.billDate ? new Date(bill.billDate).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }) : '—'

  // Left: patient info
  doc.setFontSize(7)
  doc.setTextColor(...MID)
  doc.setFont('helvetica', 'normal')
  doc.text('BILLED TO', MARGIN, y)
  y += 5
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  const patientName = bill.patient?.userId?.name || 'Patient'
  doc.text(patientName, MARGIN, y)
  y += 5
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...MID)
  if (bill.patient?.patientId) doc.text(`Patient ID: ${bill.patient.patientId}`, MARGIN, y)

  // Right: bill details
  const rightX = W - MARGIN
  let ry = 48
  const addRight = (label, value) => {
    doc.setTextColor(...MID)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7.5)
    doc.text(label, rightX - 50, ry)
    doc.setTextColor(...DARK)
    doc.setFont('helvetica', 'bold')
    doc.text(String(value), rightX, ry, { align: 'right' })
    ry += 6
  }
  addRight('Bill Date:', billDate)
  addRight('Bill Type:', bill.billType || 'Other')
  if (bill.generatedBy?.name) addRight('Generated By:', bill.generatedBy.name)

  y = Math.max(y + 10, ry + 6)

  // ── Divider ───────────────────────────────────────────────────────────────
  doc.setDrawColor(...BORDER)
  doc.line(MARGIN, y, W - MARGIN, y)
  y += 8

  // ── Items table ───────────────────────────────────────────────────────────
  // Header
  doc.setFillColor(...LIGHT)
  doc.rect(MARGIN, y - 4, COL, 10, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(...MID)
  doc.text('DESCRIPTION', MARGIN + 2, y + 2)
  doc.text('CATEGORY', MARGIN + 80, y + 2)
  doc.text('QTY', W - MARGIN - 50, y + 2, { align: 'right' })
  doc.text('UNIT PRICE', W - MARGIN - 28, y + 2, { align: 'right' })
  doc.text('AMOUNT', W - MARGIN, y + 2, { align: 'right' })
  y += 10

  // Rows
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...DARK)
  const items = bill.items || []
  items.forEach((item, i) => {
    if (i % 2 === 1) {
      doc.setFillColor(250, 252, 255)
      doc.rect(MARGIN, y - 4, COL, 9, 'F')
    }
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    const descLines = doc.splitTextToSize(item.description || '—', 75)
    doc.text(descLines, MARGIN + 2, y)
    doc.text(item.category || '—', MARGIN + 80, y)
    doc.setFont('helvetica', 'normal')
    doc.text(String(item.quantity || 1), W - MARGIN - 50, y, { align: 'right' })
    doc.text(fmt(item.unitPrice), W - MARGIN - 28, y, { align: 'right' })
    doc.setFont('helvetica', 'bold')
    doc.text(fmt(item.amount), W - MARGIN, y, { align: 'right' })
    y += descLines.length > 1 ? descLines.length * 5 + 2 : 9

    // Page break guard
    if (y > 260) {
      doc.addPage()
      y = 20
    }
  })

  y += 4
  doc.setDrawColor(...BORDER)
  doc.line(MARGIN, y, W - MARGIN, y)
  y += 8

  // ── Totals ────────────────────────────────────────────────────────────────
  const totalsX = W - MARGIN - 70
  const addTotal = (label, value, bold = false, color = DARK) => {
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    doc.setFontSize(bold ? 9 : 8)
    doc.setTextColor(...MID)
    doc.text(label, totalsX, y)
    doc.setTextColor(...color)
    doc.text(value, W - MARGIN, y, { align: 'right' })
    y += 7
  }

  addTotal('Subtotal:', fmt(bill.subtotal))
  if (bill.discount > 0)  addTotal('Discount:', `-${fmt(bill.discount)}`, false, [16, 185, 129])
  if (bill.tax > 0)       addTotal('Tax:', fmt(bill.tax))
  addTotal('Amount Paid:', fmt(bill.amountPaid), false, [16, 185, 129])

  // Total box
  doc.setFillColor(...BLUE)
  doc.roundedRect(totalsX - 4, y - 2, COL - (totalsX - MARGIN) + 4, 12, 3, 3, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.text('TOTAL AMOUNT:', totalsX, y + 6)
  doc.text(fmt(bill.totalAmount), W - MARGIN, y + 6, { align: 'right' })
  y += 18

  // Balance due
  if ((bill.balance || 0) > 0) {
    doc.setFillColor(254, 242, 242)
    doc.roundedRect(totalsX - 4, y - 2, COL - (totalsX - MARGIN) + 4, 10, 2, 2, 'F')
    doc.setTextColor(239, 68, 68)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8.5)
    doc.text('Balance Due:', totalsX, y + 4)
    doc.text(fmt(bill.balance), W - MARGIN, y + 4, { align: 'right' })
    y += 14
  }

  // ── Insurance ─────────────────────────────────────────────────────────────
  if (bill.insuranceClaim?.provider) {
    y += 4
    doc.setDrawColor(...BORDER)
    doc.line(MARGIN, y, W - MARGIN, y)
    y += 8
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8.5)
    doc.setTextColor(...DARK)
    doc.text('Insurance Details', MARGIN, y)
    y += 6
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...MID)
    const ins = bill.insuranceClaim
    if (ins.provider)       doc.text(`Provider: ${ins.provider}`, MARGIN, y), y += 5
    if (ins.claimNumber)    doc.text(`Claim #: ${ins.claimNumber}`, MARGIN, y), y += 5
    if (ins.amountClaimed)  doc.text(`Amount Claimed: ${fmt(ins.amountClaimed)}`, MARGIN, y), y += 5
    if (ins.approvedAmount) doc.text(`Approved Amount: ${fmt(ins.approvedAmount)}`, MARGIN, y), y += 5
    if (ins.status)         doc.text(`Status: ${ins.status}`, MARGIN, y), y += 5
  }

  // ── Notes ─────────────────────────────────────────────────────────────────
  if (bill.notes) {
    y += 4
    doc.setDrawColor(...BORDER)
    doc.line(MARGIN, y, W - MARGIN, y)
    y += 8
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.setTextColor(...MID)
    doc.text('Notes', MARGIN, y)
    y += 5
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...DARK)
    const noteLines = doc.splitTextToSize(bill.notes, COL)
    doc.text(noteLines, MARGIN, y)
  }

  // ── Footer ────────────────────────────────────────────────────────────────
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFillColor(...LIGHT)
    doc.rect(0, 285, W, 12, 'F')
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    doc.setTextColor(...MID)
    doc.text('MediLink Hospital Management System', MARGIN, 291)
    doc.text(`Page ${i} of ${pageCount}`, W - MARGIN, 291, { align: 'right' })
    doc.text('Thank you for choosing MediLink.', W / 2, 291, { align: 'center' })
  }

  const filename = `MediLink_Bill_${bill.billNumber || 'Invoice'}_${new Date().toISOString().slice(0, 10)}.pdf`
  doc.save(filename)
}
